
### 1
POST localhost:5000/api/register
Content-Type: application/json
{
    "email": ["lisa@gmail.com","lia@gmail.com"]
}

### 2
POST localhost:5000/api/assign
Content-Type: application/json
{
    "email" : "desi@gmail.com",
    "task" : [
        "buy egg",
        "buy milk",
        "eat"
    ]
}

### 3
POST localhost:5000/api/unassign
Content-Type: application/json
{
    "email" : "desi@gmail.com",
    "task" : [
        "eat"
    ]
}

### 4
GET localhost:5000/api/tasks/common
Content-Type: application/json
{
    "email" : ["eci@gmail.com","desi@gmail.com"]
}

